-- Upgrade from version 1.1.2 to version 1.1.3

-- This file contains sql for Oracle

------------
-- Oracle --
------------
ALTER SESSION set NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';


-- DROP TABLE PORTLET CASCADE CONSTRAINTS;

PROMPT Creating Table PORTLET ...
CREATE TABLE PORTLET (
  PORTLET_ID NUMBER(10,0) NOT NULL,
  MERCHANT_ID NUMBER(10,0) NOT NULL,
  PAGE NUMBER(10,0) NOT NULL,
  TITLE VARCHAR2(60 CHAR) NOT NULL,
  NAME VARCHAR2(100 CHAR),
  PORTLET_TYPE NUMBER(10,0) DEFAULT '0',
  LABEL_ID NUMBER(10,0) NOT NULL,
  VISIBLE NUMBER(3,0) DEFAULT '0',
  ENABLED NUMBER(3,0) DEFAULT '1',
  SORT_ORDER NUMBER(10,0) DEFAULT '0',
  COLUMN_ID VARCHAR2(20 CHAR) NOT NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_T_PORTLET on table PORTLET ... 
ALTER TABLE PORTLET
ADD CONSTRAINT PRIMARY_T_PORTLET PRIMARY KEY
(
  PORTLET_ID
)
ENABLE
;
PROMPT Creating Index IDX_PORTLET_LABEL_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_LABEL_ID_SM ON PORTLET
(
  MERCHANT_ID,
  LABEL_ID
) 
;
PROMPT Creating Index IDX_PORTLET_MERCHANT_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_MERCHANT_ID_SM ON PORTLET
(
  MERCHANT_ID
) 
;
PROMPT Creating Index IDX_PORTLET_PAGE_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_PAGE_ID_SM ON PORTLET
(
  MERCHANT_ID,
  PAGE
) 
;
PROMPT Creating Index IDX_PORTLET_PG_COL_ID_SM on PORTLET ...
CREATE INDEX IDX_PORTLET_PG_COL_ID_SM ON PORTLET
(
  MERCHANT_ID,
  PAGE,
  COLUMN_ID
) 
;



-- DROP TABLE PAGE CASCADE CONSTRAINTS;


PROMPT Creating Table PAGE ...
CREATE TABLE PAGE (
  PAGE_ID NUMBER(10,0) NOT NULL,
  MERCHANT_ID NUMBER(10,0) NOT NULL,
  HEADER CLOB,
  TITLE VARCHAR2(60 CHAR) NOT NULL,
  NAME VARCHAR2(100 CHAR),
  VISIBLE NUMBER(3,0) DEFAULT '0',
  ENABLED NUMBER(3,0) DEFAULT '1',
  SECURED NUMBER(3,0) DEFAULT '0',
  STYLE NUMBER(10,0) NOT NULL,
  PROPERTY1 VARCHAR2(120 CHAR) NULL,
  PROPERTY2 VARCHAR2(120 CHAR) NULL,
  PROPERTY3 VARCHAR2(120 CHAR) NULL,
  PROPERTY4 VARCHAR2(120 CHAR) NULL,
  PROPERTY5 VARCHAR2(120 CHAR) NULL,
  PROPERTY6 VARCHAR2(120 CHAR) NULL,
  PROPERTY7 VARCHAR2(120 CHAR) NULL,
  PROPERTY8 VARCHAR2(120 CHAR) NULL,
  PROPERTY9 VARCHAR2(120 CHAR) NULL,
  PROPERTY10 VARCHAR2(120 CHAR) NULL
);


PROMPT Creating Primary Key Constraint PRIMARY_T_PAGE on table PAGE ... 
ALTER TABLE PAGE
ADD CONSTRAINT PRIMARY_T_PAGE PRIMARY KEY
(
  PAGE_ID
)
ENABLE
;
PROMPT Creating Index IDX_PAGE_MERCHANT_ID_SM on PAGE ...
CREATE INDEX IDX_PAGE_MERCHANT_ID_SM ON PAGE
(
  PAGE_ID,
  MERCHANT_ID
) 
;
PROMPT Creating Index IDX_TITLE_MERCHANT_ID_SM on PAGE ...
CREATE INDEX IDX_TITLE_MERCHANT_ID_SM ON PAGE
(
  TITLE,
  MERCHANT_ID
) 
;

ALTER TABLE CENTRAL_SEQUENCER ADD PORTLET_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE CENTRAL_SEQUENCER ADD PAGE_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE CENTRAL_SEQUENCER ADD PAGEFLOW_ID_NEXT_VALUE NUMBER(10,0) DEFAULT '0' NOT NULL;
ALTER TABLE PRODUCTS ADD PRODUCTS_EXTERNAL_DL VARCHAR2(120 CHAR) NULL;
ALTER TABLE PRODUCTS_DESCRIPTION ADD PRODUCTS_EXTERNAL_DL VARCHAR2(120 CHAR) NULL;