-- Upgrade from version 1.1.3 to version 1.1.4

-- This file contains sql for Oracle

------------
-- Oracle --
------------
ALTER SESSION set NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

alter table ORDERS ADD DISPLAY_INVOICE_PAYMENTS NUMBER(3,0) DEFAULT '0';

alter table DYNAMIC_LABEL ADD IMAGE VARCHAR2(60 CHAR);

alter table PRODUCTS add PRODUCTS_IMAGE_1 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_2 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_3 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCTS_IMAGE_4 VARCHAR2(64 CHAR);
alter table PRODUCTS add PRODUCT_REVIEW_AVG FLOAT NULL;
alter table PRODUCTS add PRODUCT_REVIEW_COUNT NUMBER(10,0) DEFAULT 0;
alter table PRODUCTS_DESCRIPTION add PRODUCTS_TITLE VARCHAR2(120 CHAR) NULL;
alter table CATEGORIES_DESCRIPTION add CATEGORIES_TITLE VARCHAR2(120 CHAR) NULL;

insert into MODULE_CONFIGURATION (
  CONFIGURATION_MODULE,
  CONFIGURATION_KEY,
  COUNTRY_ISO_CODE_2,
  CONFIGURATION_VALUE
) values
('decotemplate','slider','XX','992px x 371px');